"""Brand mark and glow -> LVGL A8 image C arrays.

A8 keeps only alpha, the color comes from the image recolor style at runtime.
That is exactly the brand rule for the mark (white on dark, accent only as glow
around it) and it lets one glow asset serve the boot well and the orb.

  ui_img_mark_96     the four point star from brand/assets/logo.svg, 96 px
  ui_img_glow_128    radial falloff, 128 px, the "centered accent glow" from
                     brand/colors.md drawn as light rather than paint
  ui_img_star_56     the reduced star from assets_src/ui/images/orion_star.svg,
                     the centre of listening, thinking and speaking

SVGs are rasterised here, at build time, and never on the chip: LVGL's SVG
decoder pulls in ThorVG, which needs far more RAM than this board has spare.

Run from the repo root:  python firmware/assets_src/ui/tools/build_images.py
Needs Pillow.
"""
import math
import re
from pathlib import Path

from PIL import Image, ImageDraw

REPO = Path(__file__).resolve().parents[4]
SVG = REPO / "brand" / "assets" / "logo.svg"
STAR_SVG = REPO / "firmware" / "assets_src" / "ui" / "images" / "orion_star.svg"
OUT = REPO / "firmware" / "assets_src" / "ui" / "images"
SUPERSAMPLE = 8


def svg_polygon(svg=SVG):
    """The mark is one closed path of straight segments."""
    text = svg.read_text(encoding="utf-8")
    view = re.search(r'viewBox="0 0 (\d+) (\d+)"', text)
    canvas = float(view.group(1))
    d = re.search(r' d="([^"]+)"', text).group(1)
    points = [(float(x), float(y)) for x, y in re.findall(r"([\d.]+) ([\d.]+)", d)]
    return canvas, points


def render_mark(size, svg=SVG):
    canvas, points = svg_polygon(svg)
    big = size * SUPERSAMPLE
    img = Image.new("L", (big, big), 0)
    scale = big / canvas
    ImageDraw.Draw(img).polygon([(x * scale, y * scale) for x, y in points], fill=255)
    return img.resize((size, size), Image.LANCZOS)


def render_glow(size):
    """Gaussian falloff. At half radius the light is about a quarter, at the
    edge it is gone, so the object bounds never show as a disc."""
    img = Image.new("L", (size, size), 0)
    px = img.load()
    c = (size - 1) / 2.0
    sigma = 0.42 * c
    for y in range(size):
        for x in range(size):
            r = math.hypot(x - c, y - c)
            px[x, y] = round(255 * math.exp(-(r / sigma) ** 2))
    return img


def write_c(name, img):
    w, h = img.size
    data = img.tobytes()
    rows = []
    for i in range(0, len(data), w):
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + w]) + ",")
    body = "\n".join(rows)
    text = f"""// Generated by firmware/assets_src/ui/tools/build_images.py from brand/assets. Do not edit.
#include "lvgl.h"

static const uint8_t {name}_map[] = {{
{body}
}};

const lv_image_dsc_t {name} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_A8,
        .flags = 0,
        .w = {w},
        .h = {h},
        .stride = {w},
    }},
    .data_size = sizeof({name}_map),
    .data = {name}_map,
}};
"""
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f"{name}.c"
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"  {path.name}: {w}x{h}, {len(data)} bytes")


def write_jpeg_c(name, img, quality=80):
    """A JPEG as a byte array, so the camera card's decode path can be proved
    and timed on a board with no camera attached."""
    import io
    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=quality)
    data = buf.getvalue()
    rows = []
    for i in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    text = f"""// Generated by firmware/assets_src/ui/tools/build_images.py. Do not edit.
#include <stdint.h>
#include <stddef.h>

const uint8_t {name}[] = {{
{chr(10).join(rows)}
}};

const size_t {name}_len = sizeof({name});
"""
    (OUT / f"{name}.c").write_text(text, encoding="utf-8", newline="\n")
    print(f"  {name}.c: {img.size[0]}x{img.size[1]}, {len(data)} bytes jpeg")


def render_test_frame(w, h):
    """A dark cartographic grid with the mark in it. Looks like Orion, not
    like a colour bar chart, and it compresses to something camera sized."""
    img = Image.new("RGB", (w, h))
    px = img.load()
    for y in range(h):
        v = 14 + int(34 * y / h)
        for x in range(w):
            px[x, y] = (v, v + 3, v + 6)
    d = ImageDraw.Draw(img)
    for x in range(0, w, 32):
        d.line([(x, 0), (x, h)], fill=(64, 78, 86))
    for y in range(0, h, 32):
        d.line([(0, y), (w, y)], fill=(64, 78, 86))
    mark = render_mark(h // 2)
    img.paste((168, 204, 216), (w // 2 - h // 4, h // 4), mark)
    return img


def main():
    print("images")
    write_c("ui_img_mark_96", render_mark(96))
    write_c("ui_img_glow_128", render_glow(128))
    write_c("ui_img_star_56", render_mark(56, STAR_SVG))
    write_jpeg_c("ui_img_test_frame", render_test_frame(320, 240))


if __name__ == "__main__":
    main()
